<hr class="no-marg">
<section class="print_sec main_block inv_rece_footer_top">
    <div class="row">
        <div class="col-md-12">
            <h3 class="no-marg font_5 font_s_14">In Words : <?php echo $amount_in_word; ?></h3>
        </div>
    </div>
</section>

<hr class="no-marg">

<!-- invoice_receipt_footer -->
<section class="print_sec main_block inv_rece_footer_bottom">
    <div class="inv_rece_footer_signature border_block ">
        <div class="row">
            <div class="col-md-7 border_rt">
                <div class="inv_rece_footer_left">
                    <?php
                    if ($sq_terms_cond['terms_and_conditions'] != '') { ?>
                        <h3 class="no-marg font_5 font_s_14">TERMS & CONDITIONS</h3>
                        <p class="less_opact "><?= $sq_terms_cond['terms_and_conditions'] ?></p>
                    <?php } ?>
                    <div class="signature_block text-right" style="<?= empty($sq_terms_cond['terms_and_conditions'])  ? 'margin-top:50px;' : null ?>">
                        <p class="no-marg font_s_13">RECEIVER SIGNATURE</p>
                    </div>
                </div>
            </div>
            <div class="col-md-5" style="margin-bottom:0;">
                <div class="inv_rece_footer_right" style="margin-bottom:0 !important; padding:0 !important;">
                    <h3 class="no-marg font_5 font_s_12">FOR <?= $app_name ?>
                    </h3>

                    <?php
                    if (check_sign()) {
                    ?>
                        <div class="text-right">
                            <?= get_signature() ?>
                        </div>
                    <?php } ?>
                    <br>
                    <div style="text-align:right;">

                        <p class="no-marg font_s_13">AUTHORIZED SIGNATURE</p>
                        <p class="no-marg font_s_13">GENERATED BY : <?= $emp_name ?></p>
                    </div>

                </div>
            </div>
        </div>
        <br>
        <!-- <div class="signature_block signature_block_r text-right">
            <div class="row">
                <div class="col-md-12">


                </div>
            </div>
        </div> -->
    </div>

    <!-- invoice_receipt_back_detail -->
    <!-- <div class="border_block inv_rece_back_detail">
		<div class="row">
			<div class="col-md-12"><p class="border_lt"><span class="font_5">BANK NAME : </span>  ($branch_status=='yes' && $role!='Admin') ? $branch_details['bank_name'] : $bank_name_setting ?></p></div>
			<div class="col-md-6"><p class="border_lt"><span class="font_5">A/C TYPE : </span> ($branch_status=='yes' && $role!='Admin') ? $branch_details['acc_name'] : $acc_name ?></p></div>
			<div class="col-md-6"><p class="border_lt"><span class="font_5">BRANCH : </span>($branch_status=='yes' && $role!='Admin') ? $branch_details['bank_branch_name'] : $bank_branch_name ?></p></div>
			<div class="col-md-6"><p class="border_lt no-marg"><span class="font_5">A/C NO : </span> ($branch_status=='yes' && $role!='Admin') ? $branch_details['bank_acc_no'] : $bank_acc_no ?></p></div>
			<div class="col-md-6"><p class="border_lt no-marg"><span class="font_5">IFSC : </span> ($branch_status=='yes' && $role!='Admin') ? $branch_details['ifsc_code'] : $bank_ifsc_code ?></p></div>
		</div>
	</div> -->
</section>

<!-- Bottom_Note -->
<hr class="no-marg">
<section class="print_sec main_block inv_rece_footer_top">
    <div class="row">
        <div class="col-md-12">
            <h3 class="no-marg font_5 font_s_13 text-center less_opact">This is a Computer generated document and does
                not require any signature</h3>
        </div>
    </div>
</section>
<hr class="no-marg">
</body>

</html>